// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: clientCmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientCmd int32

const (
	// 通用
	ClientCmd_ClientCmdHeartbeat ClientCmd = 0 //心跳
	ClientCmd_ClientCmdLogin     ClientCmd = 1 //登录 消息体 ClientLogin
)

// Enum value maps for ClientCmd.
var (
	ClientCmd_name = map[int32]string{
		0: "ClientCmdHeartbeat",
		1: "ClientCmdLogin",
	}
	ClientCmd_value = map[string]int32{
		"ClientCmdHeartbeat": 0,
		"ClientCmdLogin":     1,
	}
)

func (x ClientCmd) Enum() *ClientCmd {
	p := new(ClientCmd)
	*p = x
	return p
}

func (x ClientCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_clientCmd_proto_enumTypes[0].Descriptor()
}

func (ClientCmd) Type() protoreflect.EnumType {
	return &file_clientCmd_proto_enumTypes[0]
}

func (x ClientCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientCmd.Descriptor instead.
func (ClientCmd) EnumDescriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{0}
}

type ClientLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *ClientLogin) Reset() {
	*x = ClientLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientCmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLogin) ProtoMessage() {}

func (x *ClientLogin) ProtoReflect() protoreflect.Message {
	mi := &file_clientCmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLogin.ProtoReflect.Descriptor instead.
func (*ClientLogin) Descriptor() ([]byte, []int) {
	return file_clientCmd_proto_rawDescGZIP(), []int{0}
}

func (x *ClientLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_clientCmd_proto protoreflect.FileDescriptor

var file_clientCmd_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x23, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x37, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientCmd_proto_rawDescOnce sync.Once
	file_clientCmd_proto_rawDescData = file_clientCmd_proto_rawDesc
)

func file_clientCmd_proto_rawDescGZIP() []byte {
	file_clientCmd_proto_rawDescOnce.Do(func() {
		file_clientCmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientCmd_proto_rawDescData)
	})
	return file_clientCmd_proto_rawDescData
}

var file_clientCmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clientCmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clientCmd_proto_goTypes = []interface{}{
	(ClientCmd)(0),      // 0: ClientCmd
	(*ClientLogin)(nil), // 1: ClientLogin
}
var file_clientCmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientCmd_proto_init() }
func file_clientCmd_proto_init() {
	if File_clientCmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientCmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientCmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clientCmd_proto_goTypes,
		DependencyIndexes: file_clientCmd_proto_depIdxs,
		EnumInfos:         file_clientCmd_proto_enumTypes,
		MessageInfos:      file_clientCmd_proto_msgTypes,
	}.Build()
	File_clientCmd_proto = out.File
	file_clientCmd_proto_rawDesc = nil
	file_clientCmd_proto_goTypes = nil
	file_clientCmd_proto_depIdxs = nil
}
