// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: serverCmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerCmd int32

const (
	// 通用
	ServerCmd_ServerCmdHeartbeat ServerCmd = 0 //心跳
	ServerCmd_ServerCmdLogin     ServerCmd = 1 //登录 消息体 ServerLogin
)

// Enum value maps for ServerCmd.
var (
	ServerCmd_name = map[int32]string{
		0: "ServerCmdHeartbeat",
		1: "ServerCmdLogin",
	}
	ServerCmd_value = map[string]int32{
		"ServerCmdHeartbeat": 0,
		"ServerCmdLogin":     1,
	}
)

func (x ServerCmd) Enum() *ServerCmd {
	p := new(ServerCmd)
	*p = x
	return p
}

func (x ServerCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_serverCmd_proto_enumTypes[0].Descriptor()
}

func (ServerCmd) Type() protoreflect.EnumType {
	return &file_serverCmd_proto_enumTypes[0]
}

func (x ServerCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerCmd.Descriptor instead.
func (ServerCmd) EnumDescriptor() ([]byte, []int) {
	return file_serverCmd_proto_rawDescGZIP(), []int{0}
}

type ServerLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
}

func (x *ServerLogin) Reset() {
	*x = ServerLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverCmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLogin) ProtoMessage() {}

func (x *ServerLogin) ProtoReflect() protoreflect.Message {
	mi := &file_serverCmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLogin.ProtoReflect.Descriptor instead.
func (*ServerLogin) Descriptor() ([]byte, []int) {
	return file_serverCmd_proto_rawDescGZIP(), []int{0}
}

func (x *ServerLogin) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_serverCmd_proto protoreflect.FileDescriptor

var file_serverCmd_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x29, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x2a, 0x37, 0x0a, 0x09,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x43, 0x6d, 0x64, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6d, 0x64, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x10, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serverCmd_proto_rawDescOnce sync.Once
	file_serverCmd_proto_rawDescData = file_serverCmd_proto_rawDesc
)

func file_serverCmd_proto_rawDescGZIP() []byte {
	file_serverCmd_proto_rawDescOnce.Do(func() {
		file_serverCmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_serverCmd_proto_rawDescData)
	})
	return file_serverCmd_proto_rawDescData
}

var file_serverCmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_serverCmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_serverCmd_proto_goTypes = []interface{}{
	(ServerCmd)(0),      // 0: ServerCmd
	(*ServerLogin)(nil), // 1: ServerLogin
}
var file_serverCmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serverCmd_proto_init() }
func file_serverCmd_proto_init() {
	if File_serverCmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serverCmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serverCmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serverCmd_proto_goTypes,
		DependencyIndexes: file_serverCmd_proto_depIdxs,
		EnumInfos:         file_serverCmd_proto_enumTypes,
		MessageInfos:      file_serverCmd_proto_msgTypes,
	}.Build()
	File_serverCmd_proto = out.File
	file_serverCmd_proto_rawDesc = nil
	file_serverCmd_proto_goTypes = nil
	file_serverCmd_proto_depIdxs = nil
}
